# See https://beta.ruff.rs/docs/configuration/

# Needed if inserting config into pyproject.toml
#[tool.ruff]

# See https://docs.astral.sh/ruff/rules/ for what these rules are.
#
# Enable at least:
#
# * pycodestyle (`E`)
# * Pyflakes (`F`)
# * Warnings (`W`)
#
# codes by default.
#
# Consider looking at "C" for yourself, probably best not included here.
# Have not yet considered whether to enable rulesets past "C" in ruff docs.

select = ["E", "F", "W", "S", "BLE", "FBT", "B", "A", "COM818"]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]

# Don't autofix unused imports; we have a lot that are implicitly exported
# via * imports to other modules
unfixable = ["F401"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".env",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "env",
    "installpoetry.py",
    "install-pdm.py"
]
per-file-ignores = {}

# Same as Black.
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"


# [tool.ruff.mccabe] if in pyproject.toml
[mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[format]
line-ending = "lf"
